-- Table: public.betting_slips

-- DROP TABLE IF EXISTS public.betting_slips;

CREATE TABLE IF NOT EXISTS public.betting_slips
(
    betting_slip_id integer NOT NULL DEFAULT nextval('betting_slips_betting_slip_id_seq'::regclass),
    user_id integer NOT NULL,
    event_id integer NOT NULL,
    amount numeric NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winning_team_id integer NOT NULL,
    CONSTRAINT betting_slips_pkey PRIMARY KEY (betting_slip_id),
    CONSTRAINT event_id FOREIGN KEY (event_id)
        REFERENCES public.events (event_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.betting_slips
    OWNER to postgres;

-- Table: public.events

-- DROP TABLE IF EXISTS public.events;

CREATE TABLE IF NOT EXISTS public.events
(
    event_id integer NOT NULL DEFAULT nextval('events_event_id_seq'::regclass),
    event_name text COLLATE pg_catalog."default" NOT NULL,
    event_date date NOT NULL,
    winning_team_id integer,
    CONSTRAINT event_id PRIMARY KEY (event_id),
    CONSTRAINT winning_team_id FOREIGN KEY (winning_team_id)
        REFERENCES public.teams (team_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.events
    OWNER to postgres;

-- Table: public.teams

-- DROP TABLE IF EXISTS public.teams;

CREATE TABLE IF NOT EXISTS public.teams
(
    team_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    team_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 5 MINVALUE 5 MAXVALUE 2147483647 CACHE 1 ),
    team_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT teams_pkey PRIMARY KEY (team_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.teams
    OWNER to postgres;



-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 3 MINVALUE 3 MAXVALUE 21412 CACHE 1 ),
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;